### Exercice 1

In [6]:
import numpy as np
impairs = np.arange(1,22,2)
impairs

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

In [8]:
pairs = [i+1 for i in impairs]
print(pairs)

[np.int64(2), np.int64(4), np.int64(6), np.int64(8), np.int64(10), np.int64(12), np.int64(14), np.int64(16), np.int64(18), np.int64(20), np.int64(22)]


In [27]:
pairs = impairs + 1
print(pairs)

[ 2  4  6  8 10 12 14 16 18 20 22]


### Exercice 2
Distance entre deux atomes carbones alpha consécutifs de la barstar

Obj: calculer la distance entre carbones alpha consécutifs le long de la chaîne peptidique avec module NumPy et de découvrir une anomalie

#### 1. Extraction des coordonnées atomiquesLecture des coordonnées

In [10]:
with open("1BTA.pdb", "r") as f_pdb, open("1BTA_CA.txt", "w") as f_CA:
    for ligne in f_pdb:
        if ligne.startswith("ATOM") and ligne[12:16].strip() == "CA":
            x = ligne[30:38]
            y = ligne[38:46]
            z = ligne[46:54]
            f_CA.write(f"{x} {y} {z} ")

#### 2. Lecture des coordonnées

In [13]:
with open("1BTA_CA.txt", "r") as f_CA:
#une liste contenant toutes les coordonnées sous forme de floats avec les fonctions split() et float()
#Affichez à l'écran le nombre total de coordonnées
    for line in f_CA:
        list_coord = [float(i) for i in line.split()] 
print(len(list_coord))

267


#### 3. Construction de la matrice de coordonnées

In [32]:
arr_coord = np.array(list_coord)
#print(arr_coord)
print(arr_coord.reshape(89,3))

[[ -7.542   5.187   9.163]
 [ -3.813   5.485   8.49 ]
 [ -1.086   3.403   6.848]
 [  2.725   3.769   6.78 ]
 [  5.117   2.213   4.245]
 [  8.545   2.232   5.905]
 [ 10.976   1.261   3.114]
 [ 13.946   1.022   5.505]
 [ 12.051  -2.069   6.699]
 [ 10.597  -3.408   3.424]
 [ 12.794  -6.261   2.2  ]
 [ 10.732  -7.258  -0.86 ]
 [  7.324  -6.831  -2.52 ]
 [  5.851  -9.332  -0.047]
 [  7.097  -7.021   2.709]
 [  5.347  -4.111   0.98 ]
 [  2.018  -5.941   0.944]
 [  2.905  -7.047   4.475]
 [  2.882  -3.573   6.019]
 [ -0.022  -2.59    3.751]
 [ -1.76   -5.68    5.122]
 [ -1.204  -4.631   8.741]
 [ -2.195  -1.004   8.212]
 [ -5.066  -1.859   5.871]
 [ -5.667  -4.86    8.158]
 [ -6.293  -7.062   5.095]
 [ -7.526 -10.643   5.529]
 [ -5.058 -13.519   5.972]
 [ -5.426 -14.409   2.279]
 [ -4.275 -10.903   1.222]
 [ -3.215 -11.796  -2.357]
 [ -0.726  -8.877  -2.011]
 [ -1.203  -8.335  -5.792]
 [ -2.609  -5.125  -7.305]
 [ -5.897  -6.886  -8.018]
 [ -6.18   -8.058  -4.401]
 [ -4.82   -4.966  -2.697]
 

#### 4. Calcul de la distance

In [33]:
n = 89
dist_mat_10 = arr_coord.resize((n-1,3))
print(dist_mat_10)
#dist_mat_79 = arr_coord.resize((,3), refcheck = False)

None
