### Exercice 1

In [6]:
import numpy as np
impairs = np.arange(1,22,2)
impairs

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

In [8]:
pairs = [i+1 for i in impairs]
print(pairs)

[np.int64(2), np.int64(4), np.int64(6), np.int64(8), np.int64(10), np.int64(12), np.int64(14), np.int64(16), np.int64(18), np.int64(20), np.int64(22)]


In [27]:
pairs = impairs + 1
print(pairs)

[ 2  4  6  8 10 12 14 16 18 20 22]


### Exercice 2
Distance entre deux atomes carbones alpha consécutifs de la barstar

Obj: calculer la distance entre carbones alpha consécutifs le long de la chaîne peptidique avec module NumPy et de découvrir une anomalie

#### 1. Extraction des coordonnées atomiquesLecture des coordonnées

In [10]:
with open("1BTA.pdb", "r") as f_pdb, open("1BTA_CA.txt", "w") as f_CA:
    for ligne in f_pdb:
        if ligne.startswith("ATOM") and ligne[12:16].strip() == "CA":
            x = ligne[30:38]
            y = ligne[38:46]
            z = ligne[46:54]
            f_CA.write(f"{x} {y} {z} ")

#### 2. Lecture des coordonnées

In [13]:
with open("1BTA_CA.txt", "r") as f_CA:
#une liste contenant toutes les coordonnées sous forme de floats avec les fonctions split() et float()
#Affichez à l'écran le nombre total de coordonnées
    for line in f_CA:
        list_coord = [float(i) for i in line.split()] 
print(len(list_coord))

267


#### 3. Construction de la matrice de coordonnées

In [46]:
arr_coord = np.array(list_coord)
#print(arr_coord)
print(arr_coord.reshape(89,3))

[[ -7.542   5.187   9.163]
 [ -3.813   5.485   8.49 ]
 [ -1.086   3.403   6.848]
 [  2.725   3.769   6.78 ]
 [  5.117   2.213   4.245]
 [  8.545   2.232   5.905]
 [ 10.976   1.261   3.114]
 [ 13.946   1.022   5.505]
 [ 12.051  -2.069   6.699]
 [ 10.597  -3.408   3.424]
 [ 12.794  -6.261   2.2  ]
 [ 10.732  -7.258  -0.86 ]
 [  7.324  -6.831  -2.52 ]
 [  5.851  -9.332  -0.047]
 [  7.097  -7.021   2.709]
 [  5.347  -4.111   0.98 ]
 [  2.018  -5.941   0.944]
 [  2.905  -7.047   4.475]
 [  2.882  -3.573   6.019]
 [ -0.022  -2.59    3.751]
 [ -1.76   -5.68    5.122]
 [ -1.204  -4.631   8.741]
 [ -2.195  -1.004   8.212]
 [ -5.066  -1.859   5.871]
 [ -5.667  -4.86    8.158]
 [ -6.293  -7.062   5.095]
 [ -7.526 -10.643   5.529]
 [ -5.058 -13.519   5.972]
 [ -5.426 -14.409   2.279]
 [ -4.275 -10.903   1.222]
 [ -3.215 -11.796  -2.357]
 [ -0.726  -8.877  -2.011]
 [ -1.203  -8.335  -5.792]
 [ -2.609  -5.125  -7.305]
 [ -5.897  -6.886  -8.018]
 [ -6.18   -8.058  -4.401]
 [ -4.82   -4.966  -2.697]
 

#### 4. Calcul de la distance

Créez maintenant une matrice qui contient les coordonnées des n-1 premiers carbones alpha et une autre qui contient les coordonnées des n-1 derniers carbones alpha. Affichez les dimensions des matrices pour vérification.
En utilisant les opérateurs mathématiques habituels (-, +, **2) et les fonctions sqrt() et sum() du module NumPy, calculez la distance entre les atomes n et n+1.

In [49]:
n = 89
arr_coord = np.resize(arr_coord,(n,3))
print(arr_coord)
dist_mat_first = np.resize(arr_coord,(n-1,3))
print(dist_mat_first)
dist_mat_last = np.resize(arr_coord[1:],(n-1,3))
print(dist_mat_last)

[[ -7.542   5.187   9.163]
 [ -3.813   5.485   8.49 ]
 [ -1.086   3.403   6.848]
 [  2.725   3.769   6.78 ]
 [  5.117   2.213   4.245]
 [  8.545   2.232   5.905]
 [ 10.976   1.261   3.114]
 [ 13.946   1.022   5.505]
 [ 12.051  -2.069   6.699]
 [ 10.597  -3.408   3.424]
 [ 12.794  -6.261   2.2  ]
 [ 10.732  -7.258  -0.86 ]
 [  7.324  -6.831  -2.52 ]
 [  5.851  -9.332  -0.047]
 [  7.097  -7.021   2.709]
 [  5.347  -4.111   0.98 ]
 [  2.018  -5.941   0.944]
 [  2.905  -7.047   4.475]
 [  2.882  -3.573   6.019]
 [ -0.022  -2.59    3.751]
 [ -1.76   -5.68    5.122]
 [ -1.204  -4.631   8.741]
 [ -2.195  -1.004   8.212]
 [ -5.066  -1.859   5.871]
 [ -5.667  -4.86    8.158]
 [ -6.293  -7.062   5.095]
 [ -7.526 -10.643   5.529]
 [ -5.058 -13.519   5.972]
 [ -5.426 -14.409   2.279]
 [ -4.275 -10.903   1.222]
 [ -3.215 -11.796  -2.357]
 [ -0.726  -8.877  -2.011]
 [ -1.203  -8.335  -5.792]
 [ -2.609  -5.125  -7.305]
 [ -5.897  -6.886  -8.018]
 [ -6.18   -8.058  -4.401]
 [ -4.82   -4.966  -2.697]
 

In [59]:
diff = dist_mat_first - dist_mat_last
distances = np.sqrt(np.sum(diff**2, axis=1))

for i, dist in enumerate(distances):
    print(f"Atoms {i+1}-{i+2}: {dist:.1f} Å")
    if dist > 4.5 or dist < 3.0:
        print(f"Valeur surprenante:{i+1} Å")

Atoms 1-2: 3.8 Å
Atoms 2-3: 3.8 Å
Atoms 3-4: 3.8 Å
Atoms 4-5: 3.8 Å
Atoms 5-6: 3.8 Å
Atoms 6-7: 3.8 Å
Atoms 7-8: 3.8 Å
Atoms 8-9: 3.8 Å
Atoms 9-10: 3.8 Å
Atoms 10-11: 3.8 Å
Atoms 11-12: 3.8 Å
Atoms 12-13: 3.8 Å
Atoms 13-14: 3.8 Å
Atoms 14-15: 3.8 Å
Atoms 15-16: 3.8 Å
Atoms 16-17: 3.8 Å
Atoms 17-18: 3.8 Å
Atoms 18-19: 3.8 Å
Atoms 19-20: 3.8 Å
Atoms 20-21: 3.8 Å
Atoms 21-22: 3.8 Å
Atoms 22-23: 3.8 Å
Atoms 23-24: 3.8 Å
Atoms 24-25: 3.8 Å
Atoms 25-26: 3.8 Å
Atoms 26-27: 3.8 Å
Atoms 27-28: 3.8 Å
Atoms 28-29: 3.8 Å
Atoms 29-30: 3.8 Å
Atoms 30-31: 3.8 Å
Atoms 31-32: 3.9 Å
Atoms 32-33: 3.8 Å
Atoms 33-34: 3.8 Å
Atoms 34-35: 3.8 Å
Atoms 35-36: 3.8 Å
Atoms 36-37: 3.8 Å
Atoms 37-38: 3.8 Å
Atoms 38-39: 3.8 Å
Atoms 39-40: 3.8 Å
Atoms 40-41: 3.8 Å
Atoms 41-42: 3.8 Å
Atoms 42-43: 3.8 Å
Atoms 43-44: 3.8 Å
Atoms 44-45: 3.8 Å
Atoms 45-46: 3.8 Å
Atoms 46-47: 3.8 Å
Atoms 47-48: 2.9 Å
Valeur surprenante:47 Å
Atoms 48-49: 3.8 Å
Atoms 49-50: 3.8 Å
Atoms 50-51: 3.8 Å
Atoms 51-52: 3.8 Å
Atoms 52-53: 3.8 Å
Atoms