### But: calculer et représenter l'axe de la première hélice alpha de la protéine 1bta.

### 1. Import libraries

In [2]:
import numpy as np

### 2. Charger le fichier

In [ ]:
coords = np.loadtxt("helix1.dat")
print(coords)
coords.shape


[[ 5.851 -9.332 -0.047]
 [ 7.097 -7.021  2.709]
 [ 5.347 -4.111  0.98 ]
 [ 2.018 -5.941  0.944]
 [ 2.905 -7.047  4.475]
 [ 2.882 -3.573  6.019]
 [-0.022 -2.59   3.751]
 [-1.76  -5.68   5.122]
 [-1.204 -4.631  8.741]
 [-2.195 -1.004  8.212]
 [-5.066 -1.859  5.871]
 [-5.667 -4.86   8.158]]


(12, 3)

### 3. Centrer les donnees


In [25]:
coords_centered = (coords - coords.mean())/coords.std()
print(coords.mean(), coords.std())
print(coords_centered.mean(), coords_centered.std())
#coords_centered

0.20755555555555552 4.971366615397758
0.0 1.0


In [29]:
cov_mat = np.cov(coords_centered.T)
cov_mat.shape
cov_mat
#np.info(np.cov)

array([[ 0.70811634, -0.2407199 , -0.38184752],
       [-0.2407199 ,  0.23009164,  0.16390166],
       [-0.38184752,  0.16390166,  0.36462633]])

In [32]:
#eigenvectors/eigenvalues

eigvals, eigvect = np.linalg.eig(cov_mat)
print(eigvals)
print(eigvect)

[1.05751211 0.13086561 0.1144566 ]
[[-0.79076457  0.49119313  0.36526797]
 [ 0.33193344  0.84546593 -0.41833904]
 [ 0.51430689  0.20956304  0.83160793]]


In [ ]:
axe = eigvect[:,0]
axe

array([-0.79076457,  0.33193344,  0.51430689])