In [1]:
import numpy as np

In [2]:
coords = np.loadtxt("helix1.dat")
coords

array([[ 5.851, -9.332, -0.047],
       [ 7.097, -7.021,  2.709],
       [ 5.347, -4.111,  0.98 ],
       [ 2.018, -5.941,  0.944],
       [ 2.905, -7.047,  4.475],
       [ 2.882, -3.573,  6.019],
       [-0.022, -2.59 ,  3.751],
       [-1.76 , -5.68 ,  5.122],
       [-1.204, -4.631,  8.741],
       [-2.195, -1.004,  8.212],
       [-5.066, -1.859,  5.871],
       [-5.667, -4.86 ,  8.158]])

In [3]:
coords_centrees = (coords - coords.mean()) / coords.std()
print(coords.mean(), coords.std())

0.20755555555555552 4.971366615397758


In [4]:
covmat = np.cov(coords_centrees.T)
covmat

array([[ 0.70811634, -0.2407199 , -0.38184752],
       [-0.2407199 ,  0.23009164,  0.16390166],
       [-0.38184752,  0.16390166,  0.36462633]])

In [5]:
eigvals, eigvecs = np.linalg.eig(covmat)
print(eigvals)
eigvecs

[1.05751211 0.13086561 0.1144566 ]


array([[-0.79076457,  0.49119313,  0.36526797],
       [ 0.33193344,  0.84546593, -0.41833904],
       [ 0.51430689,  0.20956304,  0.83160793]])

In [6]:
vec1 = eigvecs[:,0]
vec1

array([-0.79076457,  0.33193344,  0.51430689])

In [7]:
print(coords)
# Centre de masse
point_depart = coords.mean(axis=0)
point_depart

[[ 5.851 -9.332 -0.047]
 [ 7.097 -7.021  2.709]
 [ 5.347 -4.111  0.98 ]
 [ 2.018 -5.941  0.944]
 [ 2.905 -7.047  4.475]
 [ 2.882 -3.573  6.019]
 [-0.022 -2.59   3.751]
 [-1.76  -5.68   5.122]
 [-1.204 -4.631  8.741]
 [-2.195 -1.004  8.212]
 [-5.066 -1.859  5.871]
 [-5.667 -4.86   8.158]]


array([ 0.84883333, -4.80408333,  4.57791667])

In [8]:
facteur = 10
point_arrivee = point_depart + vec1*facteur
point_arrivee

array([-7.05881241, -1.48474892,  9.72098558])

In [9]:
print("draw arrow {0.84883333 -4.80408333  4.57791667} {-7.05881241 -1.48474892 9.72098558}")

draw arrow {0.84883333 -4.80408333  4.57791667} {-7.05881241 -1.48474892 9.72098558}


Cela devrait vous donner ce genre de représentation avec vmd :
![Représentation de l'axe de l'hélice dans vmd](axe_helice.png)